DROP DATABASE IF EXISTS pizzaria;
CREATE DATABASE pizzaria;

USE pizzaria;

CREATE TABLE USER(

	USR_ID INT NOT NULL AUTO_INCREMENT,
    USR_NAME VARCHAR(50) NOT NULL,
    USR_EMAIL VARCHAR(30),
    USR_PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY(USR_ID)
    
);